db:
  image: mysql
  ports:
    - '3306'
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  volumes:
    - ./Autolab/docker/mysql:/etc/mysql/conf.d
    - ./db-data:/var/lib/mysql
web:
  build: ./Autolab
  links:
    - db
  ports:
    - '80:80'
    - '443:443'
  volumes:
    - ./Autolab/courses:/home/app/webapp/courses
    - ./Autolab/assessmentConfig:/home/app/webapp/assessmentConfig
    - ./Autolab/courseConfig:/home/app/webapp/courseConfig
    - ./Autolab/gradebooks:/home/app/webapp/gradebooks
    - ./ssl:/etc/nginx/ssl
